dependencies:
 - click
 - codecov
 - ephem>=4.2
 # To make web calls
 - httpx
 - pillow
 - posix_ipc>=1.3.2
 # help dep solver
 - pyiem>=1.26.0
 - pytest-cov
 # mocking
 - pytest-httpx
 - pytest-runner
 - pytest
