dependencies:
 - click
 - codecov
 - ephem
 # help dep solver for now
 - gdal>=3.10,<3.11
 # To make web calls
 - httpx
 # Temporary solver help, REMOVEME
 - libnetcdf=4.9.2
 - pillow
 - posix_ipc>=1.3.2
 # help dep solver
 - pyiem>=1.25.0
 - pytest-cov
 # mocking
 - pytest-httpx
 - pytest-runner
 - pytest
 # dep solving help
 - rasterstats>=0.20.0
